### PR TITLE
Fix dialyxir reported issues

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
`ci.yml` is fixed because of GitHub Actions -reported warnings.
The format changes is also because of CI -reported issues.

~There's still one thing to handle potentially:~

~* Potential "The pattern can never match the type." issue found by dialyxir #123~

~(I can wait for that to either be fixed - or I can fix it if I know how)~

~which is what initially lead me to wanna introduce `dialyxir` and fix the "issues".~

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I've rebased, ran `dialyzer` on top of this new code and there's no issue. I'll move to Ready for review, but feel free to Close without merging if you think the changes aren't worth it :)

**Comment by paulo-ferraz-oliveira** [comment]
After merge, or close, though, would it be too much to ask for a release tag so your change could be imported somewhere else, pretty please? Thanks.

**Comment by josevalim** [comment]
:green_heart: :blue_heart: :purple_heart: :yellow_heart: :heart:

**Comment by josevalim** [comment]
@paulo-ferraz-oliveira do you need a new release? I thought the changes we made do not impact external libraries, only our own usage?

**Comment by paulo-ferraz-oliveira** [comment]
The ones I made, yes, only affect internally; the ones you made, though, should impact the consumer, right? (maybe not significantly is what you meant?) In any case, they'll probably eventually get updated via `mix install` when there's a new version, in the future 😄 

As an example, `absinthe` depends on `{:nimble_parsec, "~> 1.2.2 or ~> 1.3.0"}`, but without a release, if I do `mix deps.update nimble_parsec` nothing changes, right?

**Comment by josevalim** [comment]
I don't think any affect external users but I may be wrong as Dialyzer is not my strong suit. :)

**Comment by paulo-ferraz-oliveira** [comment]
I was thinking about [this change of yours](https://github.com/dashbitco/nimble_parsec/commit/15dc58df2c0ab7b6d4375f8a41281f97fae819fe), not the `dialyxir` bits, since it seems to change behaviour, but I don't know enough about the code/consumption to understand if that's the case.

**Comment by josevalim** [comment]
I don't believe it changes any user facing API or behaviour!

**Pull request merged**
